env: standard
runtime: nodejs16
service: default

handlers:
  - url: /.*
    secure: always
    script: auto

liveness_check:
  path: "/liveness_check"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
