app = "fitplot"
primary_region = "lax"

[env]
  PORT = "8080"
  NODE_ENV = "production"
  FLY = "true"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

# This Fly.io app has no [[services.ports]] because it is not open on public internet.
# Instead, this api is accessed via private networking with a Fly.io `.internal` address.
# Additionally, any public IPs allocated can be removed with the CLI via: `fly ips`
[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200

