app = "fitplot"
primary_region = "lax"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT = "8080"
  NODE_ENV = "production"
  FLY = "true"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

# This Fly.io app has no [[services.ports]] because it is not open on public internet.
# Instead, this api is accessed via private networking with a Fly.io `.internal` address.
# Additionally, any public IPs allocated can be removed with the CLI via: `fly ips`
[[services]]
  protocol = "tcp"
  internal_port = 8080

  [services.concurrency]
    type = "requests"
    hard_limit = 200
    soft_limit = 150

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    restart_limit = 6
