version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7
  gcp-cli: circleci/gcp-cli@2.4.0

jobs:
  build-and-deploy:
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout
      - node/install-packages:
          app-dir: ~/project
      - run:
          name: Build Next.js App
          command: npm run build
          working_directory: ~/project
      - gcp-cli/install
      - run:
          name: Verify gcloud CLI
          command: |
              gcloud
      # - run:
      #     name: Deploy to GAE with glcoud
      #     command: |
      #         gcloud app deploy

workflows:
  standard:
    jobs:
      - node/test:
          version: "16.13.0"
      - build-and-deploy:
          filters:
            branches:
              only:
                main
          requires:
            - node/test
      
